CREATE TABLE Products (
	[Id]		UNIQUEIDENTIFIER	NOT NULL PRIMARY KEY,
	[Name]		NVARCHAR(50)		NOT NULL,
	[Seller]	UNIQUEIDENTIFIER	NOT NULL REFERENCES Seller(Id),
	[Amount]	INT					NOT NULL DEFAULT 1,
	[DeleteDt]	DATETIME			NULL,
	[Product]	INT					NOT NULL DEFAULT 1
);