CREATE TABLE Sales (
	[Id]		UNIQUEIDENTIFIER	NOT NULL PRIMARY KEY,
	[Name]		NVARCHAR(50)		NOT NULL,
	[Id_Seller]	UNIQUEIDENTIFIER	NOT NULL REFERENCES Seller(Id),
	[Id_Buyer]	UNIQUEIDENTIFIER	NOT NULL,
	[Product]	UNIQUEIDENTIFIER	NOT NULL,
	[DeleteDt]	DATETIME			NULL
);