CREATE TABLE Seller (
	[Id]		UNIQUEIDENTIFIER	NOT NULL PRIMARY KEY,
	[Name]		NVARCHAR(50)		NOT NULL,
	[Surname]	NVARCHAR(50)		NOT NULL,
	[Phone]		NVARCHAR(50)		NOT NULL,
	[DeleteDt]	DATETIME			NULL
);